spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/urban
    username: postgres
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect